--SELECT COUNT(DISTINCT url) FROM target2pathway ;
--
--SELECT COUNT(DISTINCT id_in_source) FROM target2pathway ;
--
--SELECT
--	COUNT(id_in_source),
--	source
--FROM
--	target2pathway t2p
--GROUP BY source
--	;
--	COUNT(url),
--SELECT
--	COUNT(name),
--	source
--FROM
--	target2pathway t2p
--GROUP BY source
--	;
--
